### PR TITLE
Refuse Zookeeper standalone mode

### LINKED ISSUE #84: Zookeeper should refuse to start in standalone mode (triple split-brain)
If the `server.1`, `server.2` and `server.3` Hiera properties are not provided (or mapped incorrectly) Zookeeper will start in standalone mode. The way this Puppet module is structured, three standalone Zookeepers is an erroneous state.

This is due to the fact that the ZK manifest will proceed with or without the server list when creating the conf file for a ZK instance. According to the way ZK interpret its config, the absence of a server list will implicitly assume standalone mode. This will result in a triple split-brain that leads to data corruption among the Brokers.

Zookeeper v3.5.0 adds a config `standaloneEnabled` that will stop ZK from assuming standalone mode when no server list is specified. As of currently, this is not yet available in the Confluent Platform and this Puppet module. Until then, I suggest that the zookeeper.pp profile explicitly checks for the presence of the server list configuration and fail hard without it.

### PR DESCRIPTION
**Pull request by donastfra**
Closes #84

### CODE REVIEW

**Comment by jcustenborder** [comment]
@donastfra I see where you're going. I think this is a good direction. We should still support a single zookeeper instance but configured this way. Running a single zookeeper instance is popular on development clusters.

**Comment by donastfra** [comment]
@jcustenborder Ah, I understand your point. Agreed. Do you have any ideas on the best way of achieving this? My guess: Another Hiera property `confluent::zookeeper::standalone_mode` or similar. Make it a part of my proposed check for now and integrate it with the upcoming ZK config in v3.5.0 later. What do you think?

**Comment by jcustenborder** [comment]
@donastfra I think we can get away with doing what you are doing but only verifying `server.1`

**Comment by donastfra** [comment]
@jcustenborder I personally thing it would be more clean and future proof (for upcoming ZK version) to introduce a new parameter. I've made two more commits to demonstrate the concept. I've verified this to the best of my ability in our dev environment (actually spawned a VM and had it provisioned in standalone mode). What do you think?

**Comment by jcustenborder** [comment]
I'm going to push this out with the next release

**Comment by jcustenborder** [comment]
Thanks for the pull

**Comment by donastfra** [comment]
Thanks for the accept!

**Pull request merged**
